apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-world
  namespace: monitoring
  annotations:
        security.alpha.kubernetes.io/unsafe-sysctls: "net.core.somaxconn=65535"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-hello-world
  template:
    metadata:
      labels:
        app: go-hello-world
    spec:
      containers:
      - name: go-hello-world
        image: farnazz/go-hello-world:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: GOMAXPROCS
          value: "2"
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
